# Default values for xau-system
replicaCount: 3

image:
  repository: ghcr.io/your-org/xau-system
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: xau-system.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: xau-system-tls
      hosts:
        - xau-system.example.com

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# AI Service configuration
aiService:
  enabled: true
  replicaCount: 2
  image:
    repository: ghcr.io/your-org/xau-system-ai
    tag: "latest"
  resources:
    limits:
      cpu: 4000m
      memory: 8Gi
      nvidia.com/gpu: 1
    requests:
      cpu: 2000m
      memory: 4Gi
      nvidia.com/gpu: 1

# Database configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: "secure-password"
    database: "xau_system"
  primary:
    persistence:
      enabled: true
      size: 100Gi

# Redis configuration
redis:
  enabled: true
  auth:
    enabled: true
    password: "redis-password"

# Monitoring configuration
monitoring:
  prometheus:
    enabled: true
  grafana:
    enabled: true
    adminPassword: "admin-password"
